openapi: 3.1.0
info: {}
paths:
  /barapp.file.v1.FileService/GetFile:
    post:
      tags:
        - barapp.file.v1.FileService
      summary: GetFile is used to retrieve file meta info
      description: GetFile is used to retrieve file meta info
      operationId: barapp.file.v1.FileService.GetFile
      parameters:
        - name: Connect-Protocol-Version
          in: header
          required: true
          schema:
            $ref: '#/components/schemas/connect-protocol-version'
        - name: Connect-Timeout-Ms
          in: header
          schema:
            $ref: '#/components/schemas/connect-timeout-header'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/barapp.file.v1.GetFileRequest'
        required: true
      responses:
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/connect.error'
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/barapp.file.v1.GetFileResponse'
  /file:
    post:
      tags:
        - barapp.file.v1.FileService
      summary: UploadFile
      description: UploadFile is used to upload file with stream
      operationId: barapp.file.v1.FileService.UploadFile
      parameters:
        - name: scenario
          in: query
          schema:
            title: scenario
            description: (proto barapp.file.v1.Scenario)
            $ref: '#/components/schemas/barapp.file.v1.Scenario'
      requestBody:
        content:
          application/json:
            schema:
              title: form
              description: (proto google.api.HttpBody)
              $ref: '#/components/schemas/google.api.HttpBody'
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/barapp.file.v1.UploadFileResponse'
  /file/{id}:
    get:
      tags:
        - barapp.file.v1.FileService
      summary: DownloadFile
      description: buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
      operationId: barapp.file.v1.FileService.DownloadFile
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            title: id
            description: (proto string)
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/google.api.HttpBody'
  /greet/{name}:
    get:
      tags:
        - barapp.greet.v1.GreetService
      summary: Greet
      operationId: barapp.greet.v1.GreetService.Greet
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
            title: name
            description: (proto string)
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/barapp.greet.v1.GreetResponse'
  /namaste:
    post:
      tags:
        - fooapp.namaste.v1.NamasteService
      summary: Namaste
      operationId: fooapp.namaste.v1.NamasteService.Namaste
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/fooapp.namaste.v1.NamasteRequest'
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fooapp.namaste.v1.NamasteResponse'
components:
  schemas:
    barapp.file.v1.DownloadFileRequest:
      type: object
      properties:
        id:
          type: string
          title: id
          description: (proto string)
      title: DownloadFileRequest
      additionalProperties: false
    barapp.file.v1.GetFileRequest:
      type: object
      properties:
        id:
          type: string
          title: id
          description: (proto string)
      title: GetFileRequest
      additionalProperties: false
    barapp.file.v1.GetFileResponse:
      type: object
      properties:
        url:
          type: string
          title: url
          description: (proto string)
      title: GetFileResponse
      additionalProperties: false
    barapp.file.v1.Scenario:
      type: string
      title: Scenario
      enum:
        - SCENARIO_UNSPECIFIED
        - SCENARIO_GATEWAY
        - SCENARIO_CDN
    barapp.file.v1.UploadFileRequest:
      type: object
      properties:
        form:
          title: form
          description: (proto google.api.HttpBody)
          $ref: '#/components/schemas/google.api.HttpBody'
        scenario:
          title: scenario
          description: (proto barapp.file.v1.Scenario)
          $ref: '#/components/schemas/barapp.file.v1.Scenario'
      title: UploadFileRequest
      additionalProperties: false
    barapp.file.v1.UploadFileResponse:
      type: object
      properties:
        id:
          type: string
          title: id
          description: (proto string)
        url:
          type: string
          title: url
          description: (proto string)
      title: UploadFileResponse
      additionalProperties: false
    barapp.greet.v1.GreetRequest:
      type: object
      properties:
        name:
          type: string
          title: name
          description: (proto string)
      title: GreetRequest
      additionalProperties: false
    barapp.greet.v1.GreetResponse:
      type: object
      properties:
        message:
          type: string
          title: message
          description: (proto string)
      title: GreetResponse
      additionalProperties: false
    connect-protocol-version:
      type: number
      title: Connect-Protocol-Version
      enum:
        - 1
      description: Define the version of the Connect protocol
      const: 1
    connect-timeout-header:
      type: number
      title: Connect-Timeout-Ms
      description: Define the timeout, in ms
    connect.error:
      type: object
      properties:
        code:
          type: string
          examples:
            - not_found
          enum:
            - canceled
            - unknown
            - invalid_argument
            - deadline_exceeded
            - not_found
            - already_exists
            - permission_denied
            - resource_exhausted
            - failed_precondition
            - aborted
            - out_of_range
            - unimplemented
            - internal
            - unavailable
            - data_loss
            - unauthenticated
          description: The status code, which should be an enum value of [google.rpc.Code][google.rpc.Code].
        message:
          type: string
          description: A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the [google.rpc.Status.details][google.rpc.Status.details] field, or localized by the client.
        details:
          type: array
          items:
            $ref: '#/components/schemas/connect.error_details.Any'
          description: A list of messages that carry the error details. There is no limit on the number of messages.
      title: Connect Error
      additionalProperties: true
      description: 'Error type returned by Connect: https://connectrpc.com/docs/go/errors/#http-representation'
    connect.error_details.Any:
      type: object
      properties:
        type:
          type: string
          description: 'A URL that acts as a globally unique identifier for the type of the serialized message. For example: `type.googleapis.com/google.rpc.ErrorInfo`. This is used to determine the schema of the data in the `value` field and is the discriminator for the `debug` field.'
        value:
          type: string
          format: binary
          description: The Protobuf message, serialized as bytes and base64-encoded. The specific message type is identified by the `type` field.
        debug:
          oneOf:
            - type: object
              title: Any
              additionalProperties: true
              description: Detailed error information.
          discriminator:
            propertyName: type
          title: Debug
          description: Deserialized error detail payload. The 'type' field indicates the schema. This field is for easier debugging and should not be relied upon for application logic.
      additionalProperties: true
      description: Contains an arbitrary serialized message along with a @type that describes the type of the serialized message, with an additional debug field for ConnectRPC error details.
    fooapp.namaste.v1.NamasteRequest:
      type: object
      properties:
        name:
          type: string
          title: name
          description: (proto string)
      title: NamasteRequest
      required:
        - name
      additionalProperties: false
    fooapp.namaste.v1.NamasteResponse:
      type: object
      properties:
        message:
          type: string
          title: message
          description: (proto string)
      title: NamasteResponse
      additionalProperties: false
    google.api.HttpBody:
      type: object
      properties:
        content_type:
          type: string
          title: content_type
          description: The HTTP Content-Type header value specifying the content type of the body. (proto string)
        data:
          type: string
          title: data
          format: byte
          description: The HTTP request/response body as raw binary. (proto bytes)
        extensions:
          type: array
          items:
            $ref: '#/components/schemas/google.protobuf.Any'
          title: extensions
          description: |-
            Application specific response metadata. Must be set in the first response
             for streaming APIs. (proto google.protobuf.Any)
      title: HttpBody
      additionalProperties: false
      description: |-
        Message that represents an arbitrary HTTP body. It should only be used for
         payload formats that can't be represented as JSON, such as raw binary or
         an HTML page.


         This message can be used both in streaming and non-streaming API methods in
         the request as well as the response.

         It can be used as a top-level request field, which is convenient if one
         wants to extract parameters from either the URL or HTTP template into the
         request fields and also want access to the raw HTTP body.

         Example:

             message GetResourceRequest {
               // A unique request id.
               string request_id = 1;

               // The raw HTTP body is bound to this field.
               google.api.HttpBody http_body = 2;

             }

             service ResourceService {
               rpc GetResource(GetResourceRequest)
                 returns (google.api.HttpBody);
               rpc UpdateResource(google.api.HttpBody)
                 returns (google.protobuf.Empty);

             }

         Example with streaming methods:

             service CaldavService {
               rpc GetCalendar(stream google.api.HttpBody)
                 returns (stream google.api.HttpBody);
               rpc UpdateCalendar(stream google.api.HttpBody)
                 returns (stream google.api.HttpBody);

             }

         Use of this type only changes how the request and response bodies are
         handled, all other features will continue to work unchanged.
    google.protobuf.Any:
      type: object
      properties:
        type:
          type: string
        value:
          type: string
          format: binary
      additionalProperties: true
      description: Contains an arbitrary serialized message along with a @type that describes the type of the serialized message.
security: []
tags:
  - name: barapp.file.v1.FileService
  - name: barapp.greet.v1.GreetService
  - name: fooapp.namaste.v1.NamasteService
